version: "3.9"
services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - ./data/db-init/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-init/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user3
      MYSQL_PASSWORD: password3
      MYSQL_DATABASE: db3
    ports:
      - "3306:3306"
    volumes:
      - ./data/db-init/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql