version: "3.8"

services:
  postgresql1:
    image: postgres
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1

  postgresql2:
    image: postgres
    container_name: postgres2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: database2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2

  mysql:
    image: mysql
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql1
      MYSQL_USER: user3
      MYSQL_PASSWORD: password3
      MYSQL_ROOT_PASSWORD: rootpassword

